Use hapi-govuk-question-page plugin
DEFRA/ffc-demo-web pull request #225
Opened 2020-12-18 09:43 UTC by markysoft

PR to demonstrate using the hapi-govuk-question-page for the claims screens.

The changes incorporate GDS guidelines including - using a 2/3 width screen rather than full.
Using a field's label as the page heading when there is only one form component on a page.

Note: currently this is against a branch of the hapi-govuk-question-page plugin, but no further changes are expected to the API befioe merge.

2021-01-14 16:20 UTC, johnwatson484 requested changes
Looks really good, really like this over the current approach.

Earlier this week we've added a new question page to the journey as we needed a free text field to better support WAF testing.  If you look in the `master` branch there is now a `name` page that will need merging with this and remapped to use the npm module.  Given how much simpler the new approach is hopefully now too much effort.  The tests added as part of that will also become irrelevant so can be deleted.

Other than that, the only thing I'd like to clarify before approving relates to the `DatePartsField component.  Is there a way to add validation of an acceptable data range?  By default it allows any year after `100`.  But I can see it being a common use case within the programme that only certain dates are valid.  An example from the current world would be a customer can't activate their entitlements on a piece of land before the date they owned the land.  In the context of the demo service, we were discussing a few weeks back about adding validation to this date so the date of subsidence can't after the current day.  I had a quick look in the npm module but couldn't see an obvious way to do it?

2021-01-14 16:39 UTC, markysoft commented
Sure, I'll rebase to add the new page. 
I don't believe there is a way of annotating the route with a schema, however you could run the schema validation in the handler, and call the `failAction` from there. You can see an example of a custom post handler on the email route.

2021-01-14 16:45 UTC, johnwatson484 commented
> Sure, I'll rebase to add the new page.
> I don't believe there is a way of annotating the route with a schema, however you could run the schema validation in the handler, and call the `failAction` from there. You can see an example of a custom post handler on the email route.

Ah ok, that makes sense.  That seems a practical solution.  In that case, once the new page is added I'm happy to approve it.

2021-01-15 16:44 UTC, johnwatson484 approved these changes

2021-01-18 08:36 UTC, merged